# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: clean-posts-jekyll
email: katherinefukui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shiny clean posts.
baseurl: "/clean-posts-jekyll" # the subpath of your site, e.g. /blog
url: "http://katfukui.com" # the base hostname & protocol for your site
repo: "https://github.com/katmeister/clean-posts-jekyll"

permalink:   /demo/:title/

# Build settings
markdown: kramdown
